services:
  hireacoop:
    build: .
    container_name: hireacoop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TARGET_EMAIL=${TARGET_EMAIL}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
